name: Multi-Platform Workflow

on:
  pull_request:
    branches:
      - master

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS Info
        run: uname -a
      - name: Create and Show File
        run: |
          echo "Running on Ubuntu OS" > os_info.txt
          cat os_info.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS Info
        run: systeminfo
      - name: Create and Show File
        run: |
          echo "Running on Windows OS" > os_info.txt
          type os_info.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Show OS Info
        run: uname -a
      - name: Create and Show File
        run: |
          echo "Running on macOS OS" > os_info.txt
          cat os_info.txt

